verbatim:
  cabal-version: ">=1.10"

name: nativefiledialog
author: DSLstandard
maintainer: qgeneral35@gmail.com
version: 0.0.1
license-file: LICENSE
synopsis: >
  High-level Haskell bindings to https://github.com/btzy/nativefiledialog-extended

default-extensions:
  - AllowAmbiguousTypes
  - Arrows
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - EmptyCase
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns
ghc-options: -Wall -Wno-name-shadowing -Wno-orphans

# DEVELOPER NOTE: Link to a tutorial on using cabal flags to enable/disable
# assertions: https://guide.aelve.com/haskell/cpp-vww0qd72.html#item-oh9ytz0p
flags:
  nfd-linux-use-portal:
    description: >
      Sets the @NFD_PORTAL@ cmake flag of @nativefiledialog@.
      <https://github.com/btzy/nativefiledialog-extended> support GTK3 and
      xdg-desktop-portal on Linux. When the flag is OFF, @nativefiledialog@ uses
      GTK3. When ON, @nativefiledialog@ uses @xdg-desktop-portal@. For more
      details, refer to the README of
      <https://github.com/btzy/nativefiledialog-extended>.
    default: true
    manual: true

extra-source-files:
  - nativefiledialog-extended/CMakeLists.txt
  - nativefiledialog-extended/src/include/*
  - nativefiledialog-extended/src/*
  - nativefiledialog-extended/test/CMakeLists.txt

# build-type: Custom (hpack also sets it if the 'custom-setup' section is present)
custom-setup:
  dependencies:
    - base
    - Cabal >=1.4 && <2.1
    - directory <1.4
    - filepath <1.5
    - optics-core
    - optics-th

library:
  build-tools:
    - c2hs
  dependencies:
    - base
    - bytestring
    - filepath
    - inline-c
    - managed
    - storable-offset
    - text >= 2.1.2   # Version 2.1.2 has peekCString. We want it.
  source-dirs: src/
  include-dirs:
    - ./nativefiledialog-extended/src/include

  extra-libraries:
    - nfd

  # TIP: See nativefiledialog-extended/CMakeLists.txt to learn what libraries to
  # link.
  when:
    - condition: os(linux) && flag(nfd-linux-use-portal)
      pkgconfig-depends: dbus-1

  pkgconfig-depends: [sdl2, glfw3]
  

executables:
  cli-demo:
    source-dirs: app/
    main: CliDemo.hs
    other-modules: []
    dependencies:
      - GLFW-b
      - base
      - nativefiledialog
      - optparse-applicative
      - sdl2
      - text

  readme-demo:
    source-dirs: app/
    main: ReadmeDemo.hs
    other-modules: []
    dependencies:
      - base
      - directory
      - filepath
      - nativefiledialog
      - text
